all:
	gcc exemplo4.c -o exemplo4 cg2d.o -lm -lX11
	gcc exemplo5.c -o exemplo5 cg2d.o -lm -lX11
	gcc exemplo6.c -o exemplo6 cg2d.o -lm -lX11
	gcc exemplo7.c -o exemplo7 cg2d.o -lm -lX11
	gcc fibo.c -o fibo cg2d.o -lm -lX11
	gcc fiboc.c -o fiboc cg2d.o -lm -lX11

	